### PR TITLE
Update to use new progress keyword

### PR DESCRIPTION
**Pull request by johnarban**
This updates the backend which handles the state to use the new `progress` information implemented here https://github.com/cosmicds/hubbleds/pull/302. It will work with or without. This hasn't been tested with a class that has that feature, but it doesn't break what we currently have

### CODE REVIEW

**Comment by johnarban** [comment]
The last commit here gives us a progress where 0 is the first marker and 100% is the last marker of a stage. It requires a matching change in the hubble story here mentioned here
https://github.com/cosmicds/hubbleds/pull/302/files#r1364085422

**Comment by patudom** [comment]
Marking this as a draft because we can't fully test it until https://github.com/cosmicds/hubbleds/pull/302 is fixed so we can generate test data for this branch.

**Comment by patudom** [comment]
Making a note of this here.

https://github.com/cosmicds/educator_dashboard/pull/66#issuecomment-1773090567

**Comment by johnarban** [comment]
This is no longer relevant post-switch to Solara

**Pull request closed without merging**
